version: '2'

services:
  web:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./proyecto/odoo-web-data:/var/lib/odoo
      - ./proyecto/config:/etc/odoo
      - ./proyecto/addons:/mnt/extra-addons

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./proyecto/odoo-db-data:/var/lib/postgresql/data/pgdata

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proyecto/portainer_data:/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

volumes:
  odoo-web-data:
    driver: local
  odoo-db-data:
    driver: local
  portainer_data:
    driver: local
  addons:
    driver: local
  config:
    driver: local
